#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging:
  level:
    root: INFO
spring:
  application:
    name: inventory-service
  datasource:
    password: testpass
    url: jdbc:postgresql://localhost:5432/inventory-db
    username: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    appname: inventory-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/